language: node_js
node_js:
- '0.10'
before_script:
- yeti --server --port=9000 &
- sleep 3
addons:
  sauce_connect: true
env:
  global:
    secure: "jjh2XR2K/VrZVWnOl187riYkKJFkapdUPEKIukkinE4XlBL3Sxaq1mgEAAvak9ZJulIKNSeCSgS/6xd0L+y2AFyaGZZ4b7EpEWGVMrrHhInurrt/jLA0yFLnCbEGPu5xORmo9+Qg4HTGHduAF6hZ6qvevPzhcWbjRQX1gALVVpo="
    secure: "IiS/RewBDusC6RLcZi3T/1AxBE5fpMaML/dG4JJI1egMHCxpxANDJwtWxzFKbM3MkBxTukKqWRfGEqjDwJS5E7TPfKbjxmZRDf5LggV28PIB/x9wsZw0h5PrLDVouAkFtb8mEQaR78ohTz3NRwAxPOmsy6MTPA0wHdnVbPhXZxM="
