language: node_js
node_js:
- '0.10'
before_script:
- yeti --server --port=9000 &
- sleep 3
addons:
  sauce_connect:
    username: davit@moxiecode.com
    access_key: SAUCE_KEY
env:
  global:
    secure: anUdveu1+PbmCj3v2WAjIUFi113ZhIEahQM5kyOuyFw80wKCqoI21FEzLQmpJTtKUvgbUzVfoSg7+nPOQrWUbE+B0TrZfiGJVGw7QE7cemujYAzzQrnDcEeLWGxfSXkH+JyOiYPyCzdtkpyDKPqXo4PsOIRQ5gWo64HFmS4A8BU=
