language: node_js
node_js:
- '0.10'
before_script:
- yeti --server --port=9000 &
- sleep 3
addons:
  sauce_connect: true
env:
  global:
  - secure: BTZEvtEk109wAZKaH78k6c1Wc030znVXaXgix6wvWYmlMHAMmqCcgjvT7SmYRgbn/Wuz7p8vF1FWDe4n+48kexLm67f4EjXOE6wbh/S12EE7iYfQmE7reIYTXiO1XnnFvJJG6E7h3gMlJUtasJgkiz4YDujOJWnWPi1v1pEwdDs=
  - secure: J3FKobuZFvWPlH269Gft0Jg0oF/mTmIdhV269egqwoQeQ76+esjRog+7jsTn5hqs0IIu2OwTYy0yoNkJ7C0it1/2rnaoNtNz/z+81Me6HRluEeJpqiGKGUG3bf9xO4TVEuak/AFU/z+hYMl/shQC7AaMiNrQhZWLqYUAfLzBj5A=
